name: Update database

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout

    - name: Set up Python
      uses: actions/setup-python
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./database/requirements.txt

    - name: Run Script
      run: |
        python ./database/database_fetcher.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit and Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add ./database/database_fetcher.log
        git add ./database/database.db
        git commit -m 'Update database and log files'
        git push origin HEAD:${{ github.ref }}

    - name: Upload Log File
      uses: actions/upload-artifact
      with:
        name: database-fetcher-log
        path: ./database/database_fetcher.log

    - name: Upload Database File
      uses: actions/upload-artifact
      with:
        name: database-file
        path: ./database/database.db
